<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);USE_NSB_V7</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="NServiceBus.Persistence.Sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NsbBridgePlayground.Common\NsbBridgePlayground.Common.csproj" />
  </ItemGroup>

</Project>